name: lines
favicon: null
layout_spectrum: 0.19017953984439373
typography_spectrum: 0.9823693057987839
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
  brandStrength: 0.018259599804878235
  lightness: 0.30897112912498415
  saturation: 0.5531259439885616
  rhythmicContrast: 0.7636857409961522
purpose: []
